import { MantineProvider } from "@mantine/core";

import "./globals.css";
import { ReactNode } from "react";
import "@mantine/core/styles.css";
import '@mantine/dates/styles.css';
import '@mantine/notifications/styles.css';
export const metadata = {
    title: "My Next.js App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body>
                <MantineProvider>
                    {children}
                </MantineProvider>
            </body>
        </html>
    );
}
